name: conversion_test_2

csv_file_paths:
  file_1: ../data/synced_data/X2_SRA_A_07-05-2024_10-39-10-mod-sync.csv
  file_2: ../data/synced_data/X2_SRA_B_07-05-2024_10-41-46-mod-sync.csv

episode_stats:
  start:
    - 164041
    - 454139
    - 696306
  end:
    - 367374
    - 654139
    - 894640

decimation_factor: 5
obs_dim: 4

output_path: ../data/converted/${name}